#!/usr/bin/env bash

PATH_TO_PRM_FILES=$1
TRANSCRIPTOME_FILE=$2
TRANSCRIPTOME_FILE=${PATH_TO_PRM_FILES}/${TRANSCRIPTOME_FILE}

for FILE in ${PATH_TO_PRM_FILES}/*.prm
do
	CONTIG_ID=$(grep SEQUENCE_ID $FILE)
	CONTIG_ID=${CONTIG_ID##*=}
	GENOMA_NAME=$(grep $CONTIG_ID $TRANSCRIPTOME_FILE | cut -f1 | sort | uniq | head -n 1)
	TRANS_COORD=$(grep $CONTIG_ID $TRANSCRIPTOME_FILE | cut -f4,5 | sort | uniq | head -n 1)	
	for i in $(seq 0 4);
	do
		PENALTY=$(grep PRIMER_PAIR_${i}_PENALTY $FILE)
		PENALTY=${PENALTY##*=}
		LEFT_SEQ=$(grep PRIMER_LEFT_${i}_SEQUENCE $FILE)
		LEFT_SEQ=${LEFT_SEQ##*=}
		RIGHT_SEQ=$(grep PRIMER_RIGHT_${i}_SEQUENCE $FILE)
		RIGHT_SEQ=${RIGHT_SEQ##*=}
		LEFT_COORD=$(grep PRIMER_LEFT_${i}= $FILE)
		LEFT_COORD=${LEFT_COORD##*=}
		RIGHT_COORD=$(grep PRIMER_RIGHT_${i}= $FILE)
		RIGHT_COORD=${RIGHT_COORD##*=}
		LEFT_TM=$(grep PRIMER_LEFT_${i}_TM $FILE)
		LEFT_TM=${LEFT_TM##*=}
		RIGHT_TM=$(grep PRIMER_RIGHT_${i}_TM $FILE)
		RIGHT_TM=${RIGHT_TM##*=}
		SIZE=$(grep PRIMER_PAIR_${i}_PRODUCT_SIZE $FILE)
		SIZE=${SIZE##*=}
		if [ ! -z $SIZE ];
		then
			echo -e "$CONTIG_ID\t$GENOMA_NAME\t$TRANS_COORD\t$PENALTY\t$LEFT_SEQ\t$RIGHT_SEQ\t$LEFT_COORD\t$RIGHT_COORD\t$LEFT_TM\t$RIGHT_TM\t$SIZE"
		fi
	done
done

